#Hugo configuration
title = "Job Manager Test"
baseURL = "https:\/\/www.jobmanagertest23454.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
firstpartycookies = true
cookiedomain = "jobmanagertest23454.com"
